//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 12:10:48 PM IRST 
//


package org.cloudface.tosca.model.properties.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tMoodleDatabasePropertiesDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMoodleDatabasePropertiesDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mySqlPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConfigPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMoodleDatabasePropertiesDefinition", propOrder = {
    "dbName",
    "dbUser",
    "dbPassword",
    "mySqlPort",
    "configPath"
})
@XmlSeeAlso({
    MoodleDatabasePropertiesDefinition.class
})
public class TMoodleDatabasePropertiesDefinition {

    @XmlElement(name = "DBName")
    protected String dbName;
    @XmlElement(name = "DBUser")
    protected String dbUser;
    @XmlElement(name = "DBPassword")
    protected String dbPassword;
    protected String mySqlPort;
    @XmlElement(name = "ConfigPath")
    protected String configPath;

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the dbUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBUser() {
        return dbUser;
    }

    /**
     * Sets the value of the dbUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBUser(String value) {
        this.dbUser = value;
    }

    /**
     * Gets the value of the dbPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBPassword() {
        return dbPassword;
    }

    /**
     * Sets the value of the dbPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBPassword(String value) {
        this.dbPassword = value;
    }

    /**
     * Gets the value of the mySqlPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMySqlPort() {
        return mySqlPort;
    }

    /**
     * Sets the value of the mySqlPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMySqlPort(String value) {
        this.mySqlPort = value;
    }

    /**
     * Gets the value of the configPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigPath() {
        return configPath;
    }

    /**
     * Sets the value of the configPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigPath(String value) {
        this.configPath = value;
    }

}
