//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 03:37:53 PM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cloudface.org/schema/namespace/tosca/cream", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cloudface.tosca.model.properties.mysql;
