//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 02:34:31 PM IRST 
//


package org.cloudface.tosca.model.properties.moodle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tMoodleWebApplicationProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMoodleWebApplicationProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdminUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdminPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataRoot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMoodleWebApplicationProperties", propOrder = {
    "adminUser",
    "adminPassword",
    "dataRoot"
})
@XmlSeeAlso({
    MoodleWebApplicationProperties.class
})
public class TMoodleWebApplicationProperties {

    @XmlElement(name = "AdminUser")
    protected String adminUser;
    @XmlElement(name = "AdminPassword")
    protected String adminPassword;
    @XmlElement(name = "DataRoot")
    protected String dataRoot;

    /**
     * Gets the value of the adminUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminUser() {
        return adminUser;
    }

    /**
     * Sets the value of the adminUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminUser(String value) {
        this.adminUser = value;
    }

    /**
     * Gets the value of the adminPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * Sets the value of the adminPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminPassword(String value) {
        this.adminPassword = value;
    }

    /**
     * Gets the value of the dataRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRoot() {
        return dataRoot;
    }

    /**
     * Sets the value of the dataRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRoot(String value) {
        this.dataRoot = value;
    }

}
