//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 04:15:51 PM IRST 
//


package org.cloudface.tosca.model.properties.amazonec2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cloudface.tosca.model.properties.amazonec2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cloudface.tosca.model.properties.amazonec2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AmazonEC2Properties }
     * 
     */
    public AmazonEC2Properties createAmazonEC2Properties() {
        return new AmazonEC2Properties();
    }

    /**
     * Create an instance of {@link TAmazonEC2Properties }
     * 
     */
    public TAmazonEC2Properties createTAmazonEC2Properties() {
        return new TAmazonEC2Properties();
    }

}
